// <auto-generated />
using System;
using EntityFrameworkCore_4_5.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFrameworkCore_4_5.Migrations
{
    [DbContext(typeof(KutuphaneContext))]
    [Migration("20230324114415_ConfigSettings")]
    partial class ConfigSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.2.23128.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityFrameworkCore_4_5.Entity.Islem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("KitapAlinmaTarih")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("KitapId")
                        .HasColumnType("int");

                    b.Property<DateTime>("KitapVerilisTarih")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("DATEADD(DAY,7,getdate())");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Islems");
                });

            modelBuilder.Entity("EntityFrameworkCore_4_5.Entity.Kitap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IslemId")
                        .HasColumnType("int");

                    b.Property<string>("KitapAdi")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Kitap Adi yok");

                    b.Property<short>("Puan")
                        .HasColumnType("smallint");

                    b.Property<int>("SayfaSayisi")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<int>("TurId")
                        .HasColumnType("int");

                    b.Property<int>("YazarId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IslemId");

                    b.HasIndex("YazarId");

                    b.ToTable("Kitaps");
                });

            modelBuilder.Entity("EntityFrameworkCore_4_5.Entity.Ogrenci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("IslemId")
                        .HasColumnType("int");

                    b.Property<string>("OgrenciAd")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("OgrenciSoyad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Sinif")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IslemId");

                    b.ToTable("Ogrencis");
                });

            modelBuilder.Entity("EntityFrameworkCore_4_5.Entity.Tur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("KitapId")
                        .HasColumnType("int");

                    b.Property<string>("TurAdi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("KitapId");

                    b.ToTable("Turs");
                });

            modelBuilder.Entity("EntityFrameworkCore_4_5.Entity.Yazar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("YazarAdi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("YazarSoyadi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Yazars");
                });

            modelBuilder.Entity("EntityFrameworkCore_4_5.Entity.Kitap", b =>
                {
                    b.HasOne("EntityFrameworkCore_4_5.Entity.Islem", "Islem")
                        .WithMany("Kitaps")
                        .HasForeignKey("IslemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFrameworkCore_4_5.Entity.Yazar", "Yazar")
                        .WithMany()
                        .HasForeignKey("YazarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Islem");

                    b.Navigation("Yazar");
                });

            modelBuilder.Entity("EntityFrameworkCore_4_5.Entity.Ogrenci", b =>
                {
                    b.HasOne("EntityFrameworkCore_4_5.Entity.Islem", null)
                        .WithMany("Ogrencis")
                        .HasForeignKey("IslemId");
                });

            modelBuilder.Entity("EntityFrameworkCore_4_5.Entity.Tur", b =>
                {
                    b.HasOne("EntityFrameworkCore_4_5.Entity.Kitap", null)
                        .WithMany("Turs")
                        .HasForeignKey("KitapId");
                });

            modelBuilder.Entity("EntityFrameworkCore_4_5.Entity.Islem", b =>
                {
                    b.Navigation("Kitaps");

                    b.Navigation("Ogrencis");
                });

            modelBuilder.Entity("EntityFrameworkCore_4_5.Entity.Kitap", b =>
                {
                    b.Navigation("Turs");
                });
#pragma warning restore 612, 618
        }
    }
}
